name: Deploy Vulnerable Application                                  # workflow name

on:
  workflow_dispatch:
  push:
    branches:
      - master   

permissions:
  security-events: write
jobs:
  security_sast:
    uses: ./.github/workflows/sast-workflow.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  deploy_to_heroku:
    uses: ./.github/workflows/deploy.yml
    needs: security_sast
    secrets: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  security_dast:
    uses: ./.github/workflows/dast-workflow.yml
    needs: deploy_to_heroku